Title: About the Project
Date: 2019-7-22 16:20
lang: en

**The starting point** of our research is the observation that
naturalism, inspired by the successes of natural sciences, seems to
completely redefine competences and weaken the autonomy of
philosophy, humanitites and social sciences. In addition, we consider
also the weaker variants of naturalistic position which allow for more
reciprocal cooperation between natural sciences and other domains of
human knowledge.

**The main aim** of our research is a complex, ciritcal and
metaphilosophical analysis of the nature and foundations of
naturalism, the analysis of its relationship with philosophy in
general, and its influence on particular philosophical
subdisciplines. We also aim to evaluate the consequences which the
acceptance of basic tenets of naturalism has on our conception of
philosophy and on the ways we deal with its various subjects. The
results of our research should illuminate the overall dynamic of the
relationship between philosophy and special sciences brough about by the
application of naturalistic approach towards and within philosophy.

**Thematically**, the research is oriented towards a general
demarcation of essential features of naturalism, development of
precise and systematic distinctions between its various types, and
identification and evaluation of benefits and limits of attempts
to naturalize various philosophical issues. An essential part of
our research is also to take into account the relevant results of
special sciences, as well as proposing, on the basis of historical
sources of naturalism and its most promintent critiques, new
perspective on given philosophical approach from the point of view of
history of philosophy.

Our research is based on **assumptions**, according to which a)
naturalism is not a monolithic system of thought, but is rather
diversified according to different topics and degrees, b) from the
metaphilosophical point of view, naturalism is able to provide only a
restricted account of the nature of philosophy, and c) the success
of naturalization is specifically limited in relation to various
philosophical subdisciplines (e.g., epistemology, philosophy of mind,
ethics, social philosophy and the philosophy of mathematics).

These assumptions lead us to formulate our **basic hypothesis** as
follows:
	
> There is no generally accepted form of naturalism. The benefits
> and limits of attempts to naturalize defined topics (the nature of
> philosophy, mind, human nature, epistemic and moral norms,
> logico-mathematical objects) are specifically differentiated within
> individual subject areas.

## Partial Aims of Research Proposal

The proposal outlined above can be broken down into several partial goals
generated by various questions which arise from contemporary
theorizing of naturalism:

1. *Systematic examination of the nature of naturalism and
   classification of its various forms.*
   
	   "Naturalism" does not refer to one monolithic doctrine, but rather to
	   a plurality of theories and strategies. This calls for devising a
	   typology of different meanings and uses of the term.

2. *Development of a conceptual appartus capable to capture the ways
   in which naturalistic approach redefines the nature of philosophy.* 
   
	   From the metaphilosophical point of view, naturalism challenges us
	   to rethink the nature and relevancy of philosophy and
	   humanities. Taking the natural sciences and their methodology as an
	   ideal the philosophy should strive for, threatens the traditional
	   role occupied by the discipline or, worse, makes it obsolete.

3. *Cost-benefit analysis of naturalistic approach within the context
   of specific philosophical subdisciplines.*
   
	   Naturalism in **metaethics** is the position that all moral facts
	   are natural ones. This upsets the traditional dichotomy between
	   facts and values and may lead us to rethink the concept of human
	   nature as something that grounds the moral norms.
   
	   Inspired by impulses from biology, linguistics, AI and cognitive
	   sciences, naturalistically oriented strands in the **philosophy of
	   mind** make attempts at reinterpretation of phenomena such as
	   consciousness, self-consciousness or intentionality.
   
	   Naturalistic approaches are also wide-spread in **epistemology**,
	   where they push forward a research programme leaning heavily on
	   empirical research of cognitive processes, at times even
	   supplanting completely the traditional epistemology with such
	   research.
	   
	   In the context of **social philosophy**, naturalistic point of view
	   opens up the relationship between the biology and the social life
	   of humans, making it impossible to theorize them separately.
	   
	   We also aim to answer the question whether it is possible
	   to give a naturalisitc account of **logico-mathematical** knowledge
	   and, more generally, to naturalize abstract objects.

4. *Interpretation of findings of empirical sciences which
   inspired the attempts to naturalize traditional philosophical
   topics.*

5. *Grounding the classification of contemporary strands of naturalism
   in the analysis of its historical sources and critiques.*
   
## Research schedule

All the tasks involved in our research are spread throughout three
stages:

**July 1, 2019 - October 31, 2020:** In the first, preparatory, phase,
we aim to explain the nature of naturalism, of the
naturalization of philosophy and of its specific areas. The findings
established in this stage will be presented at a project conference
which will take place in the middle of project's timeline.

**November 1, 2020 - October 30, 2022:** In the central phase of our
research, we will deliver multidimensional and complex investigation
of its main subject, as well as of specific forms it assumes in
defined areas.

**November 1, 2022 - June 30, 2023:** Finally, we aim to evaluate and
systematize partial findings established in previous phases. This will
mainly involve organizing the concluding project conference and
preparing publications which synthesize results of our research.


 
